### ISSUE TITLE
Benchmarks with small number and "too large" number of items in the array

### ISSUE THREAD

**Issue by dumblob** [scandum/blitsort#1]
Could you also add plots of a benchmark with different number of items in the array (as you [did in benchmarks of Quadsort](https://github.com/scandum/quadsort/blob/master/images/graph2.png ))?

Especially including 4-items, 8-items, 16-items, 32-items, 230_000-items, 300_000-items, and 400_000-items array runs (i.e. very low number of items and then very large number considering its limited 512 stack).

**Comment by scandum** [comment]
I added a weighted benchmark table for 8, 32, 128, up to 524288 items.

**Comment by dumblob** [comment]
Perfect. Looks actually quite good. Thanks!
