### ISSUE TITLE
Random int test record on mac

### ISSUE THREAD

**Issue by xerox51** [scandum/blitsort#2]
I wrote a simple test program. The output revealed qsort is better than blitsort on ARM macOS when sort the random int.
And on ARM macos, the size of long long and size of long double maybe is the same.
I used gcc to compile the code, compiler said duplicated value 8byte. So I commented the line and compiled successfully.
I don't know wether the qsort implementation in c is optimized on ARM Macos or not.I'm just a noob, the code maybe have some errors. You can point out my error. My operating system is bigsur 11.0 on mac.
My code as follow:

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <errno.h>
#include <math.h>

#include "blitsort.h"

int cmp_int (const void * a, const void * b)
 {
     return ( *(int*)a - *(int*)b );
 }

long long utime()
{
	struct timeval now_time;
	gettimeofday(&now_time, NULL);
	return now_time.tv_sec * 1000000LL + now_time.tv_usec;
}

int main(){
    int a[100000],b[100000],c[100000];
    int seed = time(NULL);
    srand(seed);
    long long assignment_start_one = utime();
    for(int i = 0;i < 100000;i++){
        a[i] = rand();
    }
    for(int j = 0;j < 100000;j++){
        b[j] = a[j];
        c[j] = a[j];
    }
    long long assignment_end_one = utime();
    printf("Assignment time: %lld. \n",assignment_end_one - assignment_start_one);
    long long start = utime();
    blitsort(b,100000,sizeof(int),cmp_int);
    long long end = utime();
    long long total = end - start;
    long long start_qsort = utime();
    qsort(c,100000,sizeof(int),cmp_int);
    long long end_qsort = utime();
    long long total_qsort = end_qsort - start_qsort;
    printf("Blitsort time: %lld. \n",total);
    printf("Qsort time: %lld. \n",total_qsort);
    return 0;
}

**Comment by scandum** [comment]
Did you compile using gcc -O3 ? The binary search requires the -O3 optimization for optimal performance, and likely other routines do as well.

Your cmp_int function is incorrect, try:
```
int cmp_int(const void * a, const void * b)
{
        int fa = *(int *)a;
        int fb = *(int *)b;

        return fa - fb;
}
```

**Comment by xerox51** [comment]
Thanks!
I used the "gcc -O3 blitsorttest.c -o test" to compile the source code.
The output program revealed the blitsort is faster than qsort when sort the random int.
Thank you for your directing. I'm a noob.
