### ISSUE TITLE
Problems when building blitsort

### ISSUE THREAD

**Issue by cristiansgc** [scandum/blitsort#3]
Hello!

When building code I get lots of errors (1370 exactly). Most of them are "use of undeclared identifier" or "unknown type name". Any help here?. 

Also, what is supposed I have to pass in the last parameter of blitsort func (type CMPFUNC*)?

Thanks in advance.

**Comment by scandum** [comment]
You're compiling with gcc? Having a few of the specific warnings would help. Might be you need some headers? Could try:
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
```

Like with qsort (see man qsort) you need to provide a comparison function. bench.c has some examples.

**Comment by cristiansgc** [comment]
I'm using SEGGER embedded studio, which I think that uses gcc (not sure). 

Here I send some of the errors found. 

![Captura](https://user-images.githubusercontent.com/80602985/147951358-cda967d3-7d92-4f40-8378-54b223f20b85.JPG)

I included the headers above in this

**Comment by scandum** [comment]
Odd, maybe check the 2 errors for bench.c. As far as I can tell it's not including blitsort.h for some reason.

I never used SEGGER so I can't really help you out much.
