### ISSUE TITLE
Different license comment in blitsort.c file

### ISSUE THREAD

**Issue by lgottwald** [scandum/blitsort#5]
There is a license comment in the blitsort.c that is different to that in the repository. I guess you probably simply missed to remove that comment when you committed the license. I would appreciate if you could clarify which one applies or remove the license block in the file. Thanks a lot for the great sorting package.

**Comment by scandum** [comment]
Thanks, I forgot to remove the old license. Should be fixed now.

**Comment by lgottwald** [comment]
Thanks!
